/**
 * lib/core/create-plan.ts
 * Pure business logic for plan creation (NO console.log, NO process.exit)
 * 
 * Phase 2 Batch 1: Mutation Commands
 * Pattern: Direct import from lib/core (10-100x faster than subprocess)
 */

import { promises as fs } from 'fs';
import path from 'path';
import { generatePlanTemplate } from '../templates/plan-template.js';
import { JsonStorage } from '../context/json-storage.js';
import { detectUsername } from '../utils/git-utils.js';
import { generatePlanId } from '../utils/plan-utils.js';
import { existsSync } from 'fs';

/**
 * Options for creating a plan
 */
export interface CreatePlanCoreOptions {
  title: string;
  author?: string;
  topics?: string[];
  targetDir?: string;
}

/**
 * Result of plan creation
 */
export interface CreatePlanCoreResult {
  planId: string;
  filePath: string;
  pointerPath: string;
  created: boolean;
  metadata?: {
    title: string;
    author: string;
    topics: string[];
    status: string;
  };
}

/**
 * Create a new implementation plan
 * 
 * Pure function - NO side effects:
 * - NO console.log (caller handles output)
 * - NO process.exit (throws errors instead)
 * - Returns structured data (not stdout strings)
 * 
 * @param options - Plan creation options
 * @returns Promise resolving to plan creation result
 * @throws Error if title is invalid or file operations fail
 */
export async function createPlanCore(
  options: CreatePlanCoreOptions
): Promise<CreatePlanCoreResult> {
  const {
    title,
    author = detectUsername(),
    topics = [],
    targetDir = process.cwd()
  } = options;

  // Validation: title must be at least 3 characters
  if (!title || title.length < 3) {
    throw new Error('Plan title must be at least 3 characters');
  }

  // Always resolve to absolute path
  const resolvedTargetDir = path.resolve(targetDir);

  // Generate plan ID and filename
  const planId = generatePlanId(title);
  const filename = `${planId}.md`;
  const filepath = path.join(resolvedTargetDir, '.aiknowsys', filename);

  // Check if plan already exists
  if (existsSync(filepath)) {
    // Return early with created=false (idempotent behavior)
    const pointerPath = path.join(
      resolvedTargetDir,
      '.aiknowsys',
      'plans',
      `active-${author}.md`
    );

    return {
      planId,
      filePath: filepath,
      pointerPath,
      created: false
    };
  }

  // Generate plan content
  const content = generatePlanTemplate({
    id: planId,
    title,
    author,
    topics,
    status: 'PLANNED'
  });

  // Create .aiknowsys directory if needed
  await fs.mkdir(path.join(resolvedTargetDir, '.aiknowsys'), { recursive: true });

  // Write plan file
  await fs.writeFile(filepath, content, 'utf-8');

  // Create/update active plan pointer
  const pointerPath = path.join(
    resolvedTargetDir,
    '.aiknowsys',
    'plans',
    `active-${author}.md`
  );
  const date = new Date().toISOString().split('T')[0];

  const pointerContent = `# Active Plan: ${author}

**Plan:** [${title}](../${filename})  
**Status:** 🎯 ACTIVE  
**Started:** ${date}

---

## Progress

[Update as you work through the plan]

---

*Auto-generated by create-plan command*
`;

  // Create plans directory if needed
  await fs.mkdir(path.join(resolvedTargetDir, '.aiknowsys', 'plans'), { recursive: true });
  await fs.writeFile(pointerPath, pointerContent, 'utf-8');

  // Update context index
  const storage = new JsonStorage();
  await storage.init(resolvedTargetDir);
  await storage.rebuildIndex();

  // Return structured result
  return {
    planId,
    filePath: filepath,
    pointerPath,
    created: true,
    metadata: {
      title,
      author,
      topics,
      status: 'PLANNED'
    }
  };
}
