/**
 * lib/core/sync-plans.ts
 * Pure business logic for syncing developer plans into team index
 *
 * Phase 2 Batch 1: Architectural Fix
 * Extracted from lib/commands/sync-plans.ts to fix circular dependency
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
/**
 * Sync individual developer plans into team index (CURRENT_PLAN.md)
 *
 * Pure function - NO side effects:
 * - NO console.log (caller handles output)
 * - NO process.exit (throws errors instead)
 * - Returns structured data (not stdout strings)
 *
 * @param options - Sync options
 * @returns Promise resolving to sync result
 * @throws Error if file operations fail
 */
export async function syncPlansCore(options = {}) {
    const targetDir = resolve(options.targetDir || process.cwd());
    // Paths
    const plansDir = join(targetDir, '.aiknowsys', 'plans');
    const outputPath = join(targetDir, '.aiknowsys', 'CURRENT_PLAN.md');
    const aiknowsysDir = join(targetDir, '.aiknowsys');
    // Ensure .aiknowsys directory exists
    if (!existsSync(aiknowsysDir)) {
        const { mkdirSync } = await import('fs');
        mkdirSync(aiknowsysDir, { recursive: true });
    }
    // Check if plans directory exists
    if (!existsSync(plansDir)) {
        const content = generateEmptyIndex();
        writeFileSync(outputPath, content, 'utf-8');
        return { success: true, planCount: 0, outputPath };
    }
    // Read all active-*.md files
    const files = readdirSync(plansDir)
        .filter(f => f.startsWith('active-') && f.endsWith('.md'))
        .sort();
    if (files.length === 0) {
        const content = generateEmptyIndex();
        writeFileSync(outputPath, content, 'utf-8');
        return { success: true, planCount: 0, outputPath };
    }
    // Parse plan files
    const developers = [];
    for (const file of files) {
        const username = file.replace('active-', '').replace('.md', '');
        const filePath = join(plansDir, file);
        const content = readFileSync(filePath, 'utf-8');
        // Extract plan details
        const planMatch = content.match(/\*\*Currently Working On:\*\*\s*(.+)/);
        const statusMatch = content.match(/\*\*Status:\*\*\s*(.+)/);
        const dateMatch = content.match(/\*\*Last Updated:\*\*\s*(.+)/);
        let plan = planMatch ? planMatch[1].trim() : 'None';
        const status = statusMatch ? statusMatch[1].trim() : '📋 PLANNED';
        const lastUpdated = dateMatch ? dateMatch[1].trim() : 'Unknown';
        // Fix relative paths in plan links (plans/ dir → aiknowsys/ dir)
        // Transform first markdown link: ../PLAN_*.md → PLAN_*.md
        if (plan !== 'None' && plan.includes('[')) {
            plan = plan.replace(/\]\(\.\.\/PLAN_/, '](PLAN_');
        }
        developers.push({ username, plan, status, lastUpdated, file });
    }
    // Generate team index
    const content = generateTeamIndex(developers);
    writeFileSync(outputPath, content, 'utf-8');
    return {
        success: true,
        planCount: developers.length,
        outputPath,
        developers
    };
}
/**
 * Generate team index from developer plans
 */
function generateTeamIndex(developers) {
    const timestamp = new Date().toLocaleString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
    });
    let content = `# Current Team Plans

**Last Synced:** ${timestamp}  
**Developer Count:** ${developers.length}

> ⚠️ **AUTO-GENERATED FILE**  
> This file is automatically generated by \`npx aiknowsys sync-plans\`.  
> Manual edits will be overwritten.  
> Edit your individual plan file: \`.aiknowsys/plans/active-<username>.md\`

---

## Active Plans

| Developer | Plan | Status | Last Updated |
|-----------|------|--------|--------------|
`;
    // Add developer rows
    for (const dev of developers) {
        const planDisplay = dev.plan === 'None' ? '*No active plan*' : dev.plan;
        content += `| ${dev.username} | ${planDisplay} | ${dev.status} | ${dev.lastUpdated} |\n`;
    }
    content += `\n---

## How This Works

**For developers:**
- Your plan: \`.aiknowsys/plans/active-<your-username>.md\`
- Team sees your progress (no merge conflicts)

**For Planner:**
- Create plan in \`PLAN_*.md\`
- Update your \`active-<username>.md\` to point to it

**Sync:**
Run \`npx aiknowsys sync-plans\` to regenerate this index from individual plan files.

---

*Part of AIKnowSys multi-developer collaboration system.*
`;
    return content;
}
/**
 * Generate empty index when no plans exist
 */
function generateEmptyIndex() {
    const timestamp = new Date().toLocaleString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
    });
    return `# Current Team Plans

**Last Synced:** ${timestamp}  
**Developer Count:** 0

> ⚠️ **AUTO-GENERATED FILE**  
> This file is automatically generated by \`npx aiknowsys sync-plans\`.  
> Manual edits will be overwritten.

---

## Active Plans

*No active plans found.*

To create a plan:
1. Create \`PLAN_<name>.md\` in \`.aiknowsys/\`
2. Update \`.aiknowsys/plans/active-<username>.md\` to point to it
3. Run \`npx aiknowsys sync-plans\` to update this index

---

*Part of AIKnowSys multi-developer collaboration system.*
`;
}
//# sourceMappingURL=sync-plans.js.map