/**
 * create-plan command - Create new implementation plan
 * Phase B Mini - Context Query Completion
 */

import { promises as fs } from 'fs';
import path from 'path';
import { generatePlanTemplate } from '../templates/plan-template.js';
import { JsonStorage } from '../context/json-storage.js';
import { detectUsername } from '../utils/git-utils.js';
import { generatePlanId } from '../utils/plan-utils.js';
import { createLogger } from '../logger.js';
import { checkFileExists } from '../utils/file-utils.js';

export interface CreatePlanOptions {
  title: string;
  author?: string;
  topics?: string[];
  json?: boolean;
  targetDir?: string;
  _silent?: boolean;
}

export interface CreatePlanResult {
  planId: string;
  filePath: string;
  pointerPath: string;
  created: boolean;
}

export async function createPlan(options: CreatePlanOptions): Promise<CreatePlanResult> {
  const {
    title,
    author = detectUsername(),
    topics = [],
    json = false,
    targetDir = process.cwd(),
    _silent = false
  } = options;

  if (!title) {
    throw new Error('Plan title is required. Use: create-plan --title "Plan Name"');
  }

  // Always resolve to absolute path (Invariant #2)
  const resolvedTargetDir = path.resolve(targetDir);

  const log = createLogger(_silent || json);

  // Generate plan ID and filename
  const planId = generatePlanId(title);
  const filename = `${planId}.md`;
  const filepath = path.join(resolvedTargetDir, '.aiknowsys', filename);

  // Check if plan already exists
  await checkFileExists(filepath, {
    onExists: 'error',
    message: `Plan already exists: ${filename}`
  });

  // Generate plan content
  const content = generatePlanTemplate({
    id: planId,
    title,
    author,
    topics,
    status: 'PLANNED'
  });

  // Create .aiknowsys directory if needed
  await fs.mkdir(path.join(resolvedTargetDir, '.aiknowsys'), { recursive: true });

  // Write plan file
  await fs.writeFile(filepath, content, 'utf-8');

  // Create/update active plan pointer
  const pointerPath = path.join(resolvedTargetDir, '.aiknowsys', 'plans', `active-${author}.md`);
  const date = new Date().toISOString().split('T')[0];
  
  const pointerContent = `# Active Plan: ${author}

**Plan:** [${title}](../${filename})  
**Status:** 🎯 ACTIVE  
**Started:** ${date}

---

## Progress

[Update as you work through the plan]

---

*Auto-generated by create-plan command*
`;

  // Create plans directory if needed
  await fs.mkdir(path.join(resolvedTargetDir, '.aiknowsys', 'plans'), { recursive: true });
  await fs.writeFile(pointerPath, pointerContent, 'utf-8');

  // Update context index
  const storage = new JsonStorage();
  await storage.init(resolvedTargetDir);
  await storage.rebuildIndex();

  // Prepare response
  const result: CreatePlanResult = {
    planId,
    filePath: filepath,
    pointerPath,
    created: true
  };

  // Output
  if (json) {
    console.log(JSON.stringify(result, null, 2));
  } else if (!_silent) {
    log.success(`✅ Created plan: ${planId}`);
    log.info(`📄 Plan file: ${filepath}`);
    log.info(`🔗 Pointer: ${pointerPath}`);
    log.info('📝 Edit plan to add implementation steps');
  }

  return result;
}
