import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { createLogger } from '../logger.js';

/**
 * Sync individual developer plans into a team index (CURRENT_PLAN.md)
 * 
 * @param {Object} options - Command options
 * @param {string} options.dir - Target directory (default: current directory)
 * @param {boolean} options._silent - Silent mode for testing
 * @returns {Promise<{success: boolean, planCount: number, outputPath: string}>}
 */
export async function syncPlans(options = {}) {
  const targetDir = resolve(options.dir || process.cwd());
  const silent = options._silent || false;
  const log = createLogger(silent);

  // Paths
  const plansDir = join(targetDir, '.aiknowsys', 'plans');
  const outputPath = join(targetDir, '.aiknowsys', 'CURRENT_PLAN.md');

  // Header
  log.header('Sync Plans', '🔄');

  try {
    // Check if plans directory exists
    if (!existsSync(plansDir)) {
      log.warn('Plans directory not found. Creating minimal CURRENT_PLAN.md...');
      const content = generateEmptyIndex();
      writeFileSync(outputPath, content, 'utf-8');
      log.success('Created CURRENT_PLAN.md (no active plans)');
      return { success: true, planCount: 0, outputPath };
    }

    // Read all active-*.md files
    const files = readdirSync(plansDir)
      .filter(f => f.startsWith('active-') && f.endsWith('.md'))
      .sort();

    if (files.length === 0) {
      log.warn('No active plan files found. Creating minimal CURRENT_PLAN.md...');
      const content = generateEmptyIndex();
      writeFileSync(outputPath, content, 'utf-8');
      log.success('Created CURRENT_PLAN.md (no active plans)');
      return { success: true, planCount: 0, outputPath };
    }

    // Parse plan files
    const developers = [];
    for (const file of files) {
      const username = file.replace('active-', '').replace('.md', '');
      const filePath = join(plansDir, file);
      const content = readFileSync(filePath, 'utf-8');

      // Extract plan details
      const planMatch = content.match(/\*\*Currently Working On:\*\*\s*(.+)/);
      const statusMatch = content.match(/\*\*Status:\*\*\s*(.+)/);
      const dateMatch = content.match(/\*\*Last Updated:\*\*\s*(.+)/);

      const plan = planMatch ? planMatch[1].trim() : 'None';
      const status = statusMatch ? statusMatch[1].trim() : '📋 PLANNED';
      const lastUpdated = dateMatch ? dateMatch[1].trim() : 'Unknown';

      developers.push({ username, plan, status, lastUpdated, file });

      log.info(`Found plan: ${username} → ${plan}`);
    }

    // Generate team index
    const content = generateTeamIndex(developers);
    writeFileSync(outputPath, content, 'utf-8');

    log.success(`Synced ${developers.length} developer plan(s) → CURRENT_PLAN.md`);
    log.cyan(`\n📖 Team index: ${outputPath}`);

    return { success: true, planCount: developers.length, outputPath };

  } catch (error) {
    log.error(`Sync failed: ${error.message}`);
    throw error;
  }
}

/**
 * Generate team index from developer plans
 * @param {Array} developers - Array of developer plan objects
 * @returns {string} Markdown content for CURRENT_PLAN.md
 */
function generateTeamIndex(developers) {
  const timestamp = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  let content = `# Current Team Plans

**Last Synced:** ${timestamp}  
**Developer Count:** ${developers.length}

> ⚠️ **AUTO-GENERATED FILE**  
> This file is automatically generated by \`npx aiknowsys sync-plans\`.  
> Manual edits will be overwritten.  
> Edit your individual plan file: \`.aiknowsys/plans/active-<username>.md\`

---

## Active Plans

| Developer | Plan | Status | Last Updated |
|-----------|------|--------|--------------|
`;

  // Add developer rows
  for (const dev of developers) {
    const planDisplay = dev.plan === 'None' ? '*No active plan*' : dev.plan;
    content += `| ${dev.username} | ${planDisplay} | ${dev.status} | ${dev.lastUpdated} |\n`;
  }

  content += `\n---

## How This Works

**For developers:**
- Your plan: \`.aiknowsys/plans/active-<your-username>.md\`
- Team sees your progress (no merge conflicts)

**For Planner:**
- Create plan in \`PLAN_*.md\`
- Update your \`active-<username>.md\` to point to it

**Sync:**
Run \`npx aiknowsys sync-plans\` to regenerate this index from individual plan files.

---

*Part of AIKnowSys multi-developer collaboration system.*
`;

  return content;
}

/**
 * Generate empty index when no plans exist
 * @returns {string} Markdown content
 */
function generateEmptyIndex() {
  const timestamp = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return `# Current Team Plans

**Last Synced:** ${timestamp}  
**Developer Count:** 0

> ⚠️ **AUTO-GENERATED FILE**  
> This file is automatically generated by \`npx aiknowsys sync-plans\`.  
> Manual edits will be overwritten.

---

## Active Plans

*No active plans found.*

To create a plan:
1. Create \`PLAN_<name>.md\` in \`.aiknowsys/\`
2. Update \`.aiknowsys/plans/active-<username>.md\` to point to it
3. Run \`npx aiknowsys sync-plans\` to update this index

---

*Part of AIKnowSys multi-developer collaboration system.*
`;
}
